import { Platform, StyleSheet } from 'react-native'
import { Colors, Hp, Wp } from '../export';

export default styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: Platform.OS === 'ios' ? Colors.biruJaja : null },

    containeriOS: { flex: 1, backgroundColor: Platform.OS === 'ios' ? Colors.white : null },

    row: { flex: 1, flexDirection: 'row' },
    row_0_center: { flex: 0, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    row_center: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
    row_start: { flex: 1, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'flex-start' },
    row_end: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'flex-end' },
    row_start_center: { flex: 1, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center' },
    row_end_center: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center' },
    row_center_end: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-end' },
    row_center_start: { flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-start' },
    row_start_end: { flex: 1, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'flex-end' },
    row_0: { flex: 0, flexDirection: 'row' },

    row_0_end: { flex: 0, flexDirection: 'row', justifyContent: 'flex-end' },
    row_0_end_center: { flex: 0, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center' },


    row_space: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    row_wrap: { flex: 1, flexDirection: 'row', flexWrap: 'wrap' },

    row_space0: { flex: 0, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    row_evenly: { flex: 0, flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center' },
    row_0_start_center: { flex: 0, flexDirection: 'row', justifyContent: 'flex-start', alignItems: 'center' },
    row_space_top: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },

    row_around_center: { flex: 0, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
    row_between_center: { flex: 0, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    row_evenly_center: { flex: 0, flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center' },


    column_start_center: { flex: 1, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'center' },
    column_start_start: { flex: 1, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start' },
    column_0_start: { flex: 0, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start' },
    column_0_start_center: { flex: 0, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'center' },

    column_center_start: { flex: 1, flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start' },
    column_center: { flex: 1, flexDirection: 'column', justifyContent: 'space-evenly', alignItems: 'center' },
    column_end_center: { flex: 1, flexDirection: 'column', justifyContent: 'flex-end', alignItems: 'center' },
    column_0_center: { flex: 0, flexDirection: 'column', justifyContent: 'center', alignItems: 'center' },
    column_0_center_start: { flex: 0, flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-start' },
    column_0_center_end: { flex: 0, flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-end' },

    column: { flex: 0, flexDirection: 'column' },
    column_center_end: { flex: 0, flexDirection: 'column', justifyContent: 'center', alignItems: 'flex-end' },
    column_start: { flex: 0, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start' },
    column_start_end: { flex: 0, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-end' },
    column_end: { flex: 0, flexDirection: 'column', justifyContent: 'flex-end', alignItems: 'flex-end' },
    column_end_start: { flex: 0, flexDirection: 'column', justifyContent: 'flex-start', alignItems: 'flex-start' },

    column_around_center: { flex: 0, flexDirection: 'column', justifyContent: 'space-around', alignItems: 'center' },
    column_between_center: { flex: 0, flexDirection: 'column', justifyContent: 'space-between', alignItems: 'center' },
    column_evenly_center: { flex: 0, flexDirection: 'column', justifyContent: 'space-evenly', alignItems: 'center' },

    m: { margin: '1%' },
    m_2: { margin: '2%' },
    m_3: { margin: '3%' },
    m_4: { margin: '4%' },
    m_5: { margin: '5%' },
    mt: { marginTop: '1%' },
    mt_2: { marginTop: '2%' },
    mt_3: { marginTop: '3%' },
    mt_4: { marginTop: '4%' },
    mt_5: { marginTop: '5%' },
    mr: { marginRight: '1%' },
    mr_2: { marginRight: '2%' },
    mr_3: { marginRight: '3%' },
    mr_4: { marginRight: '4%' },
    mr_5: { marginRight: '5%' },
    ml: { marginLeft: '1%' },
    ml_2: { marginLeft: '2%' },
    ml_3: { marginLeft: '3%' },
    ml_4: { marginLeft: '4%' },
    ml_5: { marginLeft: '5%' },
    mb: { marginBottom: '1%' },
    mb_2: { marginBottom: '2%' },
    mb_3: { marginBottom: '3%' },
    mb_4: { marginBottom: '4%' },
    mb_5: { marginBottom: '5%' },
    mx: { marginHorizontal: '1%' },
    mx_2: { marginHorizontal: '2%' },
    mx_3: { marginHorizontal: '3%' },
    mx_4: { marginHorizontal: '4%' },
    mx_5: { marginHorizontal: '5%' },
    my: { marginVertical: '1%' },
    my_2: { marginVertical: '2%' },
    my_3: { marginVertical: '3%' },
    my_4: { marginVertical: '4%' },
    my_5: { marginVertical: '5%' },

    p: { padding: '1%' },
    p_2: { padding: '2%' },
    p_3: { padding: '3%' },
    p_4: { padding: '4%' },
    p_5: { padding: '5%' },
    pt: { paddingTop: '1%' },
    pt_2: { paddingTop: '2%' },
    pt_3: { paddingTop: '3%' },
    pt_4: { paddingTop: '4%' },
    pt_5: { paddingTop: '5%' },
    pr: { paddingRight: '1%' },
    pr_2: { paddingRight: '2%' },
    pr_3: { paddingRight: '3%' },
    pr_4: { paddingRight: '4%' },
    pr_5: { paddingRight: '5%' },
    pl: { paddingLeft: '1%' },
    pl_2: { paddingLeft: '2%' },
    pl_3: { paddingLeft: '3%' },
    pl_4: { paddingLeft: '4%' },
    pl_5: { paddingLeft: '5%' },
    pb: { paddingBottom: '1%' },
    pb_2: { paddingBottom: '2%' },
    pb_3: { paddingBottom: '3%' },
    pb_4: { paddingBottom: '4%' },
    pb_5: { paddingBottom: '5%' },
    px: { paddingHorizontal: '1%' },
    px_2: { paddingHorizontal: '2%' },
    px_3: { paddingHorizontal: '3%' },
    px_4: { paddingHorizontal: '4%' },
    px_5: { paddingHorizontal: '5%' },
    py: { paddingVertical: '1%' },
    py_2: { paddingVertical: '2%' },
    py_3: { paddingVertical: '3%' },
    py_4: { paddingVertical: '4%' },
    py_5: { paddingVertical: '5%' },

    font_8: { fontSize: 8, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_9: { fontSize: 9, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_10: { fontSize: 10, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_11: { fontSize: 11, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_12: { fontSize: 12, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_13: { fontSize: 13, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_14: { fontSize: 14, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_16: { fontSize: 16, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_18: { fontSize: 18, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_20: { fontSize: 20, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_22: { fontSize: 22, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_24: { fontSize: 24, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    font_26: { fontSize: 26, color: Colors.blackgrayScale, fontFamily: "Poppins-Regular", textAlignVertical: 'center' },
    text_center: { textAlign: 'center', textAlignVertical: 'center' },

    thin: { fontFamily: 'Poppins-Thin' },
    light: { fontFamily: 'Poppins-Light' },
    italic: { fontFamily: 'Poppins-Italic' },
    medium: { fontFamily: 'Poppins-Medium' },
    bold: { fontFamily: 'Poppins-Bold' },
    semi_bold: { fontFamily: 'Poppins-SemiBold' },
    extra_bold: { fontFamily: 'Poppins-ExtraBold' },

    icon_48: { width: 48, height: 48 },
    icon_30: { width: 30, height: 30, tintColor: Colors.blackgrayScale },
    icon_29: { width: 29, height: 29, tintColor: Colors.blackgrayScale },
    icon_28: { width: 28, height: 28, tintColor: Colors.blackgrayScale },
    icon_27: { width: 27, height: 27, tintColor: Colors.blackgrayScale },
    icon_26: { width: 26, height: 26, tintColor: Colors.blackgrayScale },
    icon_25: { width: 25, height: 25, tintColor: Colors.blackgrayScale },
    icon_24: { width: 24, height: 24, tintColor: Colors.blackgrayScale },
    icon_23: { width: 23, height: 23 },
    icon_21: { width: 21, height: 21 },
    icon_19: { width: 19, height: 19, tintColor: Colors.blackgrayScale },
    icon_18: { width: 18, height: 18, tintColor: Colors.blackgrayScale },
    icon_16: { width: 16, height: 16, tintColor: Colors.blackgrayScale },
    icon_14: { width: 14, height: 14, tintColor: Colors.blackgrayScale },
    icon_12: { width: 12, height: 12, tintColor: Colors.blackgrayScale },
    icon_10: { width: 10, height: 10, tintColor: Colors.blackgrayScale },

    appBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.biruJaja, height: Platform.OS === 'android' ? Hp('7%') : Hp('5.5%'), color: 'white', paddingHorizontal: Wp('4%') },
    iconHeader: { width: 50, flex: 0, justifyContent: 'center', },
    appBarIcon: { tintColor: Colors.white, width: 24, height: 24, marginRight: Wp('2%'), alignSelf: 'center' },
    appBarTouch: { backgroundColor: Colors.biruJaja, width: 38, height: 38, alignSelf: 'center', paddingLeft: '2%', borderRadius: 50, justifyContent: 'center', alignItems: 'center' },

    appBarText: { color: 'white', fontSize: 16, fontFamily: 'Poppins-SemiBold', marginBottom: '-1%' },
    appBarButton: { color: 'white', fontSize: 14, fontFamily: 'Poppins-Bold', textAlign: 'center', paddingHorizontal: Wp('2%'), justifyContent: 'center' },

    pickMedia: { flex: 1, flexDirection: 'row', justifyContent: 'space-around' },
    pickMediaButton: { flex: 1, justifyContent: 'center', alignItems: "center" },
    pickMediaIcon: { flex: 1, justifyContent: 'center', alignItems: "center", width: '40%', height: '40%' },
    pickMediaText: { fontSize: 13, color: Colors.blackLight, textAlign: 'center' },
    // width: '20%', height: '20%', 
    actionSheet: { paddingHorizontal: Wp('4%') },
    actionSheetClose: { width: 14, height: 14, tintColor: 'grey' },
    actionSheetTitle: { flex: 1, fontFamily: 'Poppins-Bold', fontSize: 17, color: Colors.biruJaja, marginTop: Hp('3%'), marginBottom: Hp('0.5%') },
    actionSheetHeader: { flex: 1, flexDirection: 'row', alignContent: 'space-between', alignItems: 'center' },
    appBarRow: { flex: 1, flexDirection: 'row', alignItems: 'center', borderBottomColor: '#C0C0C0', borderBottomWidth: 0.2, width: Wp('100%'), paddingVertical: Wp('4%') },
    smallTextAlert: { fontSize: 11, color: '#9A9A9A', marginBottom: Hp('0%'), },
    smallTextAlertError: { fontSize: 11, color: 'red', marginBottom: Hp('0%'), borderTopColor: '#9A9A9A', borderTopWidth: 0.5 },



    header: { flex: 0, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', height: Platform.OS === 'android' ? Hp('7%') : Hp('5.5%'), elevation: 1, paddingHorizontal: '4%', backgroundColor: Colors.biruJaja, },
    headerTitle: { fontSize: 16, color: Colors.black, },
    search: { flexDirection: 'row', paddingHorizontal: '3%', borderRadius: 5, flex: 1, marginHorizontal: '0.5%', marginVertical: '3%', backgroundColor: Colors.whiteGrey },
    searchCard: { paddingHorizontal: '3%', borderRadius: 5, margin: '2%', backgroundColor: '#C0C0C0' },

    // icon
    arrowBack: { tintColor: Colors.white, width: 27, height: 27, alignSelf: 'flex-end', marginRight: Wp('1%') },

    // shadow card
    shadow_3: { shadowColor: "#000", shadowOffset: { width: 0, height: 1, }, shadowOpacity: 0.22, shadowRadius: 2.22, elevation: 3, },
    shadow_5: { shadowColor: "#000", shadowOffset: { width: 0, height: 2, }, shadowOpacity: 0.25, shadowRadius: 3.84, elevation: 5, },

    //image 
    iconDelete: { position: 'absolute', right: Wp('0%'), top: Hp('0%'), marginRight: Wp('4.5%'), width: 21, height: 21, backgroundColor: '#CC0000', borderRadius: 100 },
    iconDeleteImage: { alignSelf: "center", width: 8, height: 8, resizeMode: 'contain', flex: 1, borderRadius: 25, tintColor: Colors.white },

    // event
    scrollHorizontal: { justifyContent: 'center', alignItems: 'center', height: Hp('6%'), paddingHorizontal: '2.5%' },

    TI_RightIcon: { position: 'absolute', width: 25, height: 25, right: 10, bottom: 15 },

    FL_TouchAble: { borderBottomColor: Colors.silver, borderBottomWidth: 1, paddingVertical: '3%' },
    FL_TouchAbleItem: { fontSize: 14, color: Colors.blackgrayScale, fontFamily: 'Poppins-Regular' },

})

